from typing import List
from db import TrackDatabase, TrackRecord
from helper import build_audio_vector


SEED_TRACKS: List[TrackRecord] = [
    # =========================================================================
    # GENRE 1: Synthwave / Darkwave (Cohesive Group - 4 tracks)
    # =========================================================================
    TrackRecord(
        title="Corridor of Cyan",
        artist=["The Draftmaster"],
        genre=["synthwave", "electronic"],
        year=2024,
        duration=215000,
        acousticness=0.02,
        danceability=0.68,
        energy=0.82,
        instrumentalness=0.85,
        loudness=-6.4,
        mode=1,
        speechiness=0.04,
        tempo=120.0,
        valence=0.45,
        lore="Indigo neon washes over a long glass hallway where time stands still.",
    ),
    TrackRecord(
        title="Redraft at Midnight",
        artist=["The Draftmaster"],
        genre=["synthwave", "darkwave"],
        year=2025,
        duration=198000,
        acousticness=0.01,
        danceability=0.72,
        energy=0.88,
        instrumentalness=0.78,
        loudness=-5.2,
        mode=0,
        speechiness=0.05,
        tempo=124.0,
        valence=0.38,
        lore="A hum of high-voltage conduits echoes beneath a dark steel floor.",
    ),
    TrackRecord(
        title="46th Room Sequence",
        artist=["Vector Syndicate"],
        genre=["synthwave", "electronic"],
        year=2023,
        duration=240000,
        acousticness=0.05,
        danceability=0.64,
        energy=0.75,
        instrumentalness=0.91,
        loudness=-7.1,
        mode=1,
        speechiness=0.03,
        tempo=118.0,
        valence=0.52,
        lore="Cold glass monitors reflect glowing grid lines across a silent terminal.",
    ),
    TrackRecord(
        title="Gridlines & Shadows",
        artist=["Vector Syndicate", "The Draftmaster"],
        genre=["synthwave"],
        year=2026,
        duration=210000,
        acousticness=0.03,
        danceability=0.61,
        energy=0.79,
        instrumentalness=0.82,
        loudness=-6.8,
        mode=0,
        speechiness=0.04,
        tempo=122.0,
        valence=0.29,
        lore="Flickering indicator lights cast long shadows down an empty ramp.",
    ),
    # =========================================================================
    # GENRE 2: Classical / Chamber Music (Cohesive Group - 4 tracks)
    # =========================================================================
    TrackRecord(
        title="Waltz for an Undrawn Door",
        artist=["Baroness von Mt. Holly"],
        genre=["classical", "chamber music"],
        year=1998,
        duration=285000,
        acousticness=0.95,
        danceability=0.32,
        energy=0.18,
        instrumentalness=0.94,
        loudness=-18.2,
        mode=1,
        speechiness=0.03,
        tempo=84.0,
        valence=0.15,
        lore="Moonlight streams through cracked stained glass onto damp velvet.",
    ),
    TrackRecord(
        title="Elegy for Room 0",
        artist=["Baroness von Mt. Holly"],
        genre=["classical"],
        year=2001,
        duration=310000,
        acousticness=0.98,
        danceability=0.25,
        energy=0.12,
        instrumentalness=0.96,
        loudness=-22.5,
        mode=0,
        speechiness=0.04,
        tempo=68.0,
        valence=0.08,
        lore="Dust motes drift above a forgotten grand piano in a locked parlor.",
    ),
    TrackRecord(
        title="Sanctuary Blueprint No. 3",
        artist=["The Architectural Quartet"],
        genre=["classical", "chamber music"],
        year=2012,
        duration=260000,
        acousticness=0.91,
        danceability=0.38,
        energy=0.24,
        instrumentalness=0.89,
        loudness=-16.1,
        mode=1,
        speechiness=0.03,
        tempo=92.0,
        valence=0.22,
        lore="Weathered oak paneling absorbs the quiet murmur of a bowing cello.",
    ),
    TrackRecord(
        title="The Foundation String Quartet",
        artist=["The Architectural Quartet"],
        genre=["classical"],
        year=2015,
        duration=275000,
        acousticness=0.93,
        danceability=0.29,
        energy=0.21,
        instrumentalness=0.92,
        loudness=-17.8,
        mode=0,
        speechiness=0.03,
        tempo=76.0,
        valence=0.18,
        lore="A high marble vault carries the fading echo of a single violin.",
    ),
    # =========================================================================
    # GENRE 3: Ambient / Drone (Cohesive Group - 4 tracks)
    # =========================================================================
    TrackRecord(
        title="Subterranean Reservoir",
        artist=["Echoes of Holly"],
        genre=["ambient", "drone"],
        year=2021,
        duration=380000,
        acousticness=0.88,
        danceability=0.12,
        energy=0.08,
        instrumentalness=0.98,
        loudness=-28.4,
        mode=0,
        speechiness=0.03,
        tempo=60.0,
        valence=0.05,
        lore="Black water laps against stone pillars beneath a forgotten bridge.",
    ),
    TrackRecord(
        title="Static in the Conservatory",
        artist=["Echoes of Holly"],
        genre=["ambient"],
        year=2022,
        duration=340000,
        acousticness=0.82,
        danceability=0.15,
        energy=0.11,
        instrumentalness=0.95,
        loudness=-24.1,
        mode=1,
        speechiness=0.04,
        tempo=65.0,
        valence=0.12,
        lore="Overgrown ivy clings to iron beams in a fog-choked glasshouse.",
    ),
    TrackRecord(
        title="Drafting Table Resonances",
        artist=["Null Floor"],
        genre=["ambient", "drone"],
        year=2020,
        duration=410000,
        acousticness=0.76,
        danceability=0.09,
        energy=0.06,
        instrumentalness=0.97,
        loudness=-30.0,
        mode=0,
        speechiness=0.03,
        tempo=55.0,
        valence=0.03,
        lore="Brass rulers and velum sheets lie frozen under a faint hum.",
    ),
    TrackRecord(
        title="Anteroom Silence",
        artist=["Null Floor"],
        genre=["ambient"],
        year=2024,
        duration=320000,
        acousticness=0.85,
        danceability=0.18,
        energy=0.14,
        instrumentalness=0.93,
        loudness=-22.0,
        mode=1,
        speechiness=0.04,
        tempo=70.0,
        valence=0.19,
        lore="A closed door blocks the hallway while soft air drifts through grates.",
    ),
    # =========================================================================
    # GENRE 4: Cool Jazz / Noir (Cohesive Group - 4 tracks)
    # =========================================================================
    TrackRecord(
        title="Midnight in the Parlor",
        artist=["The Brass Key Trio"],
        genre=["cool jazz", "jazz"],
        year=2017,
        duration=230000,
        acousticness=0.62,
        danceability=0.55,
        energy=0.34,
        instrumentalness=0.71,
        loudness=-14.2,
        mode=0,
        speechiness=0.04,
        tempo=108.0,
        valence=0.48,
        lore="Cigar smoke swirls around leather chairs and a half-empty glass.",
    ),
    TrackRecord(
        title="Keycard Lounge",
        artist=["The Brass Key Trio"],
        genre=["cool jazz"],
        year=2019,
        duration=215000,
        acousticness=0.58,
        danceability=0.58,
        energy=0.39,
        instrumentalness=0.68,
        loudness=-12.8,
        mode=1,
        speechiness=0.05,
        tempo=112.0,
        valence=0.54,
        lore="Dim amber wall sconces illuminate a polished mahogany bar.",
    ),
    TrackRecord(
        title="The Hidden Staircase Strut",
        artist=["Miles & The Blueprints"],
        genre=["jazz", "bebop"],
        year=2010,
        duration=205000,
        acousticness=0.49,
        danceability=0.62,
        energy=0.48,
        instrumentalness=0.63,
        loudness=-11.0,
        mode=0,
        speechiness=0.06,
        tempo=130.0,
        valence=0.61,
        lore="A bronze handrail spirals downward into a warm, wood-lined cellar.",
    ),
    TrackRecord(
        title="Whispers in the Library",
        artist=["Miles & The Blueprints"],
        genre=["cool jazz"],
        year=2014,
        duration=250000,
        acousticness=0.65,
        danceability=0.48,
        energy=0.28,
        instrumentalness=0.75,
        loudness=-15.5,
        mode=1,
        speechiness=0.04,
        tempo=96.0,
        valence=0.41,
        lore="Towering oak bookshelves cast long shadows on a green banker lamp.",
    ),
    # =========================================================================
    # GENRE 5: Indie Folk / Acoustic (Cohesive Group - 4 tracks)
    # =========================================================================
    TrackRecord(
        title="Overgrown Garden Gate",
        artist=["The Orchard Draft"],
        genre=["indie folk", "acoustic"],
        year=2018,
        duration=190000,
        acousticness=0.89,
        danceability=0.46,
        energy=0.32,
        instrumentalness=0.15,
        loudness=-12.1,
        mode=1,
        speechiness=0.03,
        tempo=102.0,
        valence=0.65,
        lore="Rays of morning sun break through ivy onto a weathered stone bench.",
    ),
    TrackRecord(
        title="Pebbles in the Cloister Pool",
        artist=["The Orchard Draft"],
        genre=["indie folk"],
        year=2021,
        duration=205000,
        acousticness=0.86,
        danceability=0.51,
        energy=0.29,
        instrumentalness=0.22,
        loudness=-13.5,
        mode=1,
        speechiness=0.04,
        tempo=98.0,
        valence=0.58,
        lore="Ripples spread across a quiet stone basin surrounded by white lilies.",
    ),
    TrackRecord(
        title="Courtyard in Autumn",
        artist=["Cora & The Architecture"],
        genre=["indie folk", "acoustic"],
        year=2016,
        duration=225000,
        acousticness=0.92,
        danceability=0.42,
        energy=0.25,
        instrumentalness=0.08,
        loudness=-14.8,
        mode=0,
        speechiness=0.03,
        tempo=88.0,
        valence=0.39,
        lore="Crisp fallen leaves scrape across cobblestones in a chill breeze.",
    ),
    TrackRecord(
        title="The Gardener's Blueprint",
        artist=["Cora & The Architecture"],
        genre=["indie folk"],
        year=2019,
        duration=198000,
        acousticness=0.87,
        danceability=0.49,
        energy=0.35,
        instrumentalness=0.12,
        loudness=-11.9,
        mode=1,
        speechiness=0.04,
        tempo=106.0,
        valence=0.71,
        lore="A wooden potting shed smells of rich soil, cedar, and dried lavender.",
    ),
    # =========================================================================
    # WILDCARD / CROSS-REALM REALMS (10 tracks in drastically different realms)
    # =========================================================================
    # Realm 1: Industrial Noise / Machine Metal
    TrackRecord(
        title="Boiler Room Surge",
        artist=["Furnace 46"],
        genre=["industrial", "noise"],
        year=2025,
        duration=175000,
        acousticness=0.001,
        danceability=0.35,
        energy=0.96,
        instrumentalness=0.88,
        loudness=-2.1,
        mode=0,
        speechiness=0.12,
        tempo=150.0,
        valence=0.11,
        lore="Piston steam fills an iron chamber as massive gears turn below.",
    ),
    TrackRecord(
        title="Pressure Gauge Breakdown",
        artist=["Furnace 46"],
        genre=["industrial"],
        year=2026,
        duration=188000,
        acousticness=0.002,
        danceability=0.29,
        energy=0.98,
        instrumentalness=0.92,
        loudness=-1.8,
        mode=0,
        speechiness=0.15,
        tempo=162.0,
        valence=0.07,
        lore="Red warning lamps flash along a narrow catwalk suspended over fire.",
    ),
    # Realm 2: Baroque Choral / Sacred
    TrackRecord(
        title="Cantata for the Grand Hall",
        artist=["The Estate Choir"],
        genre=["baroque", "choral"],
        year=1985,
        duration=320000,
        acousticness=0.96,
        danceability=0.18,
        energy=0.31,
        instrumentalness=0.05,
        loudness=-15.2,
        mode=1,
        speechiness=0.04,
        tempo=72.0,
        valence=0.33,
        lore="Wordless vocal harmonies reverberate off high stone vaulted ceilings.",
    ),
    TrackRecord(
        title="Miserere of the Hidden Passages",
        artist=["The Estate Choir"],
        genre=["choral"],
        year=1990,
        duration=355000,
        acousticness=0.97,
        danceability=0.14,
        energy=0.22,
        instrumentalness=0.02,
        loudness=-18.4,
        mode=0,
        speechiness=0.04,
        tempo=64.0,
        valence=0.12,
        lore="Echoing soprano lines soar down an empty gallery of ancestral portraits.",
    ),
    # Realm 3: High-BPM Math Rock / Post-Punk
    TrackRecord(
        title="Infinite Draft Loop",
        artist=["Angle & Polygon"],
        genre=["math rock", "post-punk"],
        year=2023,
        duration=182000,
        acousticness=0.04,
        danceability=0.52,
        energy=0.91,
        instrumentalness=0.55,
        loudness=-4.8,
        mode=1,
        speechiness=0.08,
        tempo=174.0,
        valence=0.68,
        lore="Jangled guitar riffing rattles the brass door fittings in a tight loop.",
    ),
    TrackRecord(
        title="Shifted Floorplan Shifted Mind",
        artist=["Angle & Polygon"],
        genre=["math rock"],
        year=2024,
        duration=195000,
        acousticness=0.06,
        danceability=0.48,
        energy=0.87,
        instrumentalness=0.62,
        loudness=-5.5,
        mode=0,
        speechiness=0.07,
        tempo=168.0,
        valence=0.51,
        lore="Interlocking drum polyrhythms echo down a zig-zagging corridor.",
    ),
    # Realm 4: Minimalist Vaporwave / Mallsoft
    TrackRecord(
        title="Elevator to the Observatory",
        artist=["Mt. Holly Shopping Complex"],
        genre=["vaporwave", "mallsoft"],
        year=2015,
        duration=210000,
        acousticness=0.38,
        danceability=0.62,
        energy=0.33,
        instrumentalness=0.85,
        loudness=-14.0,
        mode=1,
        speechiness=0.04,
        tempo=82.0,
        valence=0.42,
        lore="Muffled brass music leaks through carpeted walls of an empty atrium.",
    ),
    TrackRecord(
        title="Fountain Plaza 1999",
        artist=["Mt. Holly Shopping Complex"],
        genre=["vaporwave"],
        year=2017,
        duration=228000,
        acousticness=0.41,
        danceability=0.65,
        energy=0.28,
        instrumentalness=0.81,
        loudness=-15.8,
        mode=1,
        speechiness=0.05,
        tempo=78.0,
        valence=0.49,
        lore="Pastel tiled planters surround a stagnant pool under a tinted skylight.",
    ),
    # Realm 5: Traditional Celtic Folk / Pipe
    TrackRecord(
        title="Lament for the West Wing",
        artist=["The Highland Draft"],
        genre=["celtic folk", "world"],
        year=2008,
        duration=245000,
        acousticness=0.89,
        danceability=0.41,
        energy=0.55,
        instrumentalness=0.78,
        loudness=-9.8,
        mode=0,
        speechiness=0.04,
        tempo=116.0,
        valence=0.31,
        lore="A wooden flute hums across a mist-covered outdoor terrace at dawn.",
    ),
    TrackRecord(
        title="Hedge Maze Reel",
        artist=["The Highland Draft"],
        genre=["celtic folk"],
        year=2011,
        duration=210000,
        acousticness=0.84,
        danceability=0.68,
        energy=0.72,
        instrumentalness=0.69,
        loudness=-8.1,
        mode=1,
        speechiness=0.05,
        tempo=138.0,
        valence=0.79,
        lore="High-energy fiddle melodies bound off tall yew hedges in the sunlight.",
    ),
]


def seed_database():
    db = TrackDatabase()
    print("Seeding Supabase catalog...")
    for i, track in enumerate(SEED_TRACKS):
        track_id = track.isrc+str(i)
        track.isrc = track.mbid = track.recco_id = track.spotify_id = track_id
        track.audio_vector = build_audio_vector(track)
        db.insert_track(track)
    print("Seeded titles:")
    cat = db.fetch_catalog()
    for track in cat:
        print(track.title)

seed_database()
